### ISSUE TITLE
[AVM Module Issue]: add argument key_vault_id to app_service_certificate

### ISSUE THREAD

**Issue by rbradley51** [Azure/terraform-azurerm-avm-res-web-site#102]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

To allow cross subscription key vault access, please add argument key_vault_id to azurerm_app_service_certificate

`>= 3.95.0`

**Comment by donovm4** [comment]
@rbradley51 - will take a look into this shortly.

**Comment by donovm4** [comment]
@rbradley51 - please review the latest published release `v0.8.0`
