### ISSUE TITLE
[AVM Module Issue]: Setting logs.http_logs.file_system also requires setting azure_blob_storage_http

### ISSUE THREAD

**Issue by philipstreet** [Azure/terraform-azurerm-avm-res-web-site#106]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.8.1

### Description

# Issue
I'm trying to create a Linux Web App, replicating the `application logging` configuration from an existing resource, as per;

![avm-web-issue](https://github.com/user-attachments/assets/13862ef7-045d-4939-8174-7ea18fc859a8)

Here's some code I'm using;

``` hcl
module "backend-web-app" {
  source                                         = "Azure/avm-res-web-site/azurerm"
  version                                        = "0.8.1"
  enable_telemetry                               = false
  resource_group_name                            = azurerm_resource_group.this.name
  location                                       = azurerm_resource_group.this.location
  os_type                                        = var.backend_app_service_plan_os_type
  kind                                           = "webapp"
  name                                           = var.backend_app_service_name
  create_service_plan                            = false
  service_plan_resource_id                       = azurerm_service_plan.this.id
  logs = {
      "log_config" = {
        http_logs = {
          "http_log" = {
            file_system = {
              retention_in_days = 30
              retention_in_mb   = 35
            }
          }
        }
      }
    }
}
```

The Terraform docs show both http_logs and azure_blob_storage as optional;

![avm-web-issue-2](https://github.com/user-attachments/assets/20ea245a-c8f4-4826-8a2a-96e1b750094c)

There's no "Note" indicating that only one or at least one is required.

# Expected Behaviour
I can set the application log config using the http_logs block only.

# Actual Behaviour
I get the following Terraform Plan error;

```
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/backend/main.web_app.tf line 964, in resource "azurerm_linux_web_app" "this":
│  964:             sas_url           = http_logs.value.azure_blob_storage.sas_url
│     ├────────────────
│     │ http_logs.value is object with 2 attributes
│ 
│ This object does not have an attribute named "azure_blob_storage".
╵
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/backend/main.web_app.tf line 965, in resource "azurerm_linux_web_app" "this":
│  965:             retention_in_days = http_logs.value.azure_blob_storage.retention_in_days
│     ├────────────────
│     │ http_logs.value is object with 2 attributes
│ 
│ This object does not have an attribute named "azure_blob_storage".
```

**Comment by rbradley51** [comment]
I'm receiving similar errors. the sas_url is required, not sure if that's what's causing it. 

![image](https://github.com/user-attachments/assets/6af2f916-8c13-45cc-b3f3-12f66aea7c90)

![image](https://github.com/user-attachments/assets/98d02cac-2cc8-418b-aa74-c5b010318e96)

i'd expect the same error for http but the content is set to `azure_blob_storage` not `azure_blob_storage_http`

![image](https://github.com/user-attachments/assets/c28635b2-9ccb-461b-becb-90a7963fbf79)

![image](https://github.com/user-attachments/assets/74513429-508b-4ec8-a9d9-28358fff34d3)

![image](https://github.com/user-attachments/assets/276b0308-bd7e-416a-bd54-90e11cee698c)

**Comment by donovm4** [comment]
@philipstreet + @rbradley51:

Will look into this shortly.

**Comment by donovm4** [comment]
@philipstreet + @rbradley51:

Please review `v0.9.0` as the latest release and test out the new functionality for `logs`. 

I have added `example`/`logs` to assist with both of your use cases.

Let me know if I can assist further with this issue.

**Comment by philipstreet** [comment]
@donovm4 That's fixed it for me, thanks!
