### ISSUE TITLE
[AVM Module Issue]: The azurerm_windows_function_app site config is missing ip_restriction_default_action and scm_ip_restriction_default_action

### ISSUE THREAD

**Issue by rpandey-agl** [Azure/terraform-azurerm-avm-res-web-site#120]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.10.0

### (Optional) Correlation Id

The azurerm_windows_function_app site config is missing ip_restriction_default_action and scm_ip_restriction_default_action

### Description

The azurerm_windows_function_app site config is missing ip_restriction_default_action and scm_ip_restriction_default_action

**Comment by MikeDembek** [comment]
I see this as well, the value for ip_restriction_default_action is ignored and hits the default "Allow" defined for ip_restriction_default_action in azurerm_windows_functin_app.

**Comment by donovm4** [comment]
@rpandey-agl + @MikeDembek : 

I will be looking into this. The module is currently going through refactoring to better align with `resource` module specifications, but I will investigate this regardless.

**Comment by donovm4** [comment]
@rpandey-agl + @MikeDembek : 

Please send the latest release of the module. Be aware that it includes some breaking changes, so be sure to review the release notes.

Let me know if you need any assistance with current configurations that may be affected.
