### ISSUE TITLE
bug: ``use_32_bit_worker`` defaults to true

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-web-site#13]
Ref:

https://github.com/Azure/terraform-azurerm-avm-res-web-site/blob/352266444bdc63a5da10864014bd8b954bbce471/variables.tf#L689

However, the comment says it defaults to false (which I think is preferable as it aligns with the Hashicorp defaults)

**Comment by donovm4** [comment]
addressed in release v0.1.1
