### ISSUE TITLE
[AVM Question/Feedback]: Can auth_settings_v2 add a default login argument

### ISSUE THREAD

**Issue by dribblor** [Azure/terraform-azurerm-avm-res-web-site#130]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Terraform fails with the error `element "example": attribute "login" is required.` when using the auth_settings_v2 from the example in the readme. E.g.

```
auth_settings_v2 = {
  example = {
    auth_enabled = true
    active_directory_v2 = {
      client_id                  = "00000000-0000-0000-0000-000000000000"
      client_secret_setting_name = "00000000-0000-0000-0000-000000000000"
      login_scopes               = ["00000000-0000-0000-0000-000000000000"]
    }
  }
}
```

Can the variable defaults or dynamic block in the module be configured such that I don't have to provide it with an empty login argument?

Below is what I'm having to do when calling the module which looks messy, but I can't see how to tweak the module to _default to an empty login block unless one is provided_.

```
      login = {
        login1 = {}
      }
```

**Comment by donovm4** [comment]
@dribblor : 

According to the azurerm provider [here](https://registry.terraform.io/providers/hashicorp/azurerm/4.7.0/docs/resources/windows_web_app#login), the login block says required; however, I can review to see if there is something that I can do to address this.

**Comment by donovm4** [comment]
@dribblor : 

Please review release `0.12.0` and release notes. 

I have added a default `login` block and updated the documentation with a better example for `auth_settings_v2`. Also review the actual `examples` \ `basic_auth` deployment example as well.

Please let me know if you have any more questions / issues.

**Comment by dribblor** [comment]
Looks great, thank you :)
