### ISSUE TITLE
[AVM Module Issue]: Missing variable mapping for slot.site_config.virtual_application

### ISSUE THREAD

**Issue by purduebretty** [Azure/terraform-azurerm-avm-res-web-site#140]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

Updating settings for deployment_slots.site_config.virtual_application don't appear to map to value in main.web_app_slots.tf.

Steps to recreate:

1. Create windows_web_app with a staging slot using module
2. Redeploy web app, it will show state has changed because azure has set the virtual_application settings to the default, but the module will plan for a null value

**Comment by donovm4** [comment]
Hello @purduebretty : 

I will be looking into this shortly.

**Comment by donovm4** [comment]
@purduebretty : 

Please review latest module release of `v0.12.1`

**Comment by purduebretty** [comment]
Hi Donovan,
Thanks for hopping on that.  I'm using other modules that require ~>3.71 so I'm unable to test it with my current config, but I reviewed the changes and they look good.
