### ISSUE TITLE
[AVM Module Issue]: Dotnet core parameter missing in within site_config (application_stack) but present in main

### ISSUE THREAD

**Issue by elbatane** [Azure/terraform-azurerm-avm-res-web-site#146]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

latest

### Description

The variable site_config does not have dotnetcore parameter within application_stack block. However, the logic for it is ready in the main file.

**Comment by donovm4** [comment]
Hi @elbatane - I will look into this shortly 👍

**Comment by donovm4** [comment]
@elbatane - please view the latest version and its release notes.

Will mark as fixed, but please reach out should something not be properly addressed.
