### ISSUE TITLE
Incorrect permissions

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-azurerm-avm-res-web-site#2]
Hi! please can you add @Azure/avm-core-team-technical-terraform to the repo admins?

**Comment by segraef** [comment]
@donovm4

**Comment by segraef** [comment]
> Hi! please can you add @Azure/avm-core-team-technical-terraform to the repo admins?

@donovm4

**Comment by donovm4** [comment]
@Azure/avm-core-team-technical-terraform has been added.
