### ISSUE TITLE
[AVM Module Issue]: Missing application_stack input vars

### ISSUE THREAD

**Issue by jamie-oconnell** [Azure/terraform-azurerm-avm-res-web-site#31]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.1

### Description

application_stack Input variables for Linux webapp are missing.

```
This object does not have an attribute named "go_version"
This object does not have an attribute named "java_server".
This object does not have an attribute named "java_server_version".
This object does not have an attribute named "php_version".
This object does not have an attribute named "ruby_version".
```

**Comment by donovm4** [comment]
I have pushed a PR to address needed linting error fixes in order for the current PR for this bug to be addressed
