### ISSUE TITLE
[AVM Module Issue]: Missing virtual_application support in site_settings for Windows webapp

### ISSUE THREAD

**Issue by rzand** [Azure/terraform-azurerm-avm-res-web-site#52]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.4.0

### Description

The terraform plan keeps adding the below:
      ~ site_config {
            # (23 unchanged attributes hidden)

          + virtual_application {
              + physical_path = "site\\wwwroot"
              + preload       = false
              + virtual_path  = "/"
            }

            # (1 unchanged block hidden)
        }

**Comment by donovm4** [comment]
Hi @rzand - will be taking a look into this soon.

**Comment by donovm4** [comment]
It seems this is a provider issue, specifically when `always_on` feature is turned off. I will see if I can find a workaround in the meantime.

Please find the issue opened [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/16326).

**Comment by donovm4** [comment]
addressed in release v0.5.0
