### ISSUE TITLE
[AVM Module Issue]: APPINSIGHTS_INSTRUMENTATIONKEY missing in application settings

### ISSUE THREAD

**Issue by luisarnauth** [Azure/terraform-azurerm-avm-res-web-site#55]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

When enabling Application Insights, the **APPLICATIONINSIGHTS_CONNECTION_STRING** application setting is added from the azurerm_application_insights resource deployed by the module:

```hcl
app_settings = var.enable_application_insights ? merge({ "APPLICATIONINSIGHTS_CONNECTION_STRING" = azurerm_application_insights.this[0].connection_string }, var.app_settings) : var.app_settings
```

But just adding this setting is not enough, as Application Insights will show up as not enabled in the Azure Portal.

Adding the **APPINSIGHTS_INSTRUMENTATIONKEY** to the application setting will ensure that Application Insights is enabled in the Azure Portal:

```hcl
app_settings = var.enable_application_insights ? merge(
    { "APPLICATIONINSIGHTS_CONNECTION_STRING" = azurerm_application_insights.this[0].connection_string },
    { "APPINSIGHTS_INSTRUMENTATIONKEY" = azurerm_application_insights.this[0].instrumentation_key },
    var.app_settings
  ) : var.app_settings
```

Just tested with a Linux Web App, but probably it will be required for Windows Web App and both Linux and Windows Functions.

**Comment by donovm4** [comment]
addressed in release v0.5.0
