### ISSUE TITLE
[AVM Module Issue]: missing Slot

### ISSUE THREAD

**Issue by sven5** [Azure/terraform-azurerm-avm-res-web-site#64]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Hi guys,

we're working heavily with deployment slots (ie. `azurerm_linux_web_app_slot`). However, I cannot find this feature in this module.`So please add.

**Comment by donovm4** [comment]
Hi @sven5 - although there is overlap between the resources, I will need to check internally to see if this should be a feature for this module, or if a new `resource` / `pattern` module should be created.

**Comment by donovm4** [comment]
HI @sven5 - after some feedback from internal team, will work to add this as a feature request for the module.

**Comment by donovm4** [comment]
Hello again @sven5 - I will be publishing a new version with an example of using deployment slots. Feel free to provide feedback once it is published 👍

**Comment by donovm4** [comment]
`v0.7.0` is now published. There is an `example` called `slot` that will provide a sample configuration.

**Please review the release notes for `v0.7.0` as there are also so major changes.**

**Comment by rbradley51** [comment]
Hi @donovm4 - could you add support for Private Endpoints?
