### ISSUE TITLE
[AVM Module Issue]: authorization_endpoint  vs authorisation_endpoint while setting up custom_oidc_v2 block 

### ISSUE THREAD

**Issue by vaiddas** [Azure/terraform-azurerm-avm-res-web-site#66]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.5.0

### Description

https://github.com/Azure/terraform-azurerm-avm-res-web-site/blob/8b30573c0014d6bca35c560d6bc694fe39b8b3c9/main.web_app.tf#L354
          authorisation_endpoint        = custom_oidc_v2.value.authorisation_endpoint

**Note the "s" in the authorisation spelling** 
 
Now look the variables.tf where this variable is declared: 
      authorization_endpoint        = optional(string)

**Note the "z" in the spelling instead of "s"**

https://github.com/Azure/terraform-azurerm-avm-res-web-site/blob/8b30573c0014d6bca35c560d6bc694fe39b8b3c9/variables.tf#L261
 
so I see an error like below:
 
│ Error: Unsupported attribute
│
│   on .terraform\modules\test\main.web_app.tf line 845, in resource "azurerm_linux_web_app" "this":
│  845:           authorisation_endpoint        = custom_oidc_v2.value.authorisation_endpoint
│     ├────────────────
│     │ custom_oidc_v2.value is object with 11 attributes
│
│ This object does not have an attribute named "authorisation_endpoint".

**Comment by donovm4** [comment]
Hi @vaiddas - will look into this shortly.

**Comment by donovm4** [comment]
addressed in v0.6.0 release
