### ISSUE TITLE
[AVM Module Issue]:  Terraform 1.6.0 Crash with the module

### ISSUE THREAD

**Issue by vaiddas** [Azure/terraform-azurerm-avm-res-web-site#70]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

Steps to reproduce:

1-) Install Terraform 1.6.0 
2-) Run TF plan with just required inputs.

Expected Result: 
Terraform Plan should work

Actual Result:
Terraform Crash Error. 

Please note it works fine with TF 1.6.1

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
Terraform crashed! This is always indicative of a bug within Terraform.
Please report the crash with Terraform[1] so that we can fix this.
 
When reporting bugs, please include your terraform version, the stack trace
shown below, and any additional information which may help replicate the issue.
 
[1]: https://github.com/hashicorp/terraform/issues
 
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
value is marked, so must be unmarked first
goroutine 501 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:16 +0x13
github.com/hashicorp/terraform/internal/logging.PanicHandler()
        /home/runner/work/terraform/terraform/internal/logging/panic.go:58 +0x13b
panic({0x2b87000?, 0x38c33a0?})
        /opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:920 +0x270
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.0/cty/marks.go:141
.........
...................
..........................

```

**Comment by donovm4** [comment]
Hello @vaiddas - will look into this shortly

**Comment by matt-FFFFFF** [comment]
Hi!

Please log this on the terraform repo and this isn't a module issue.

Have you tried a later version of Terraform?

**Comment by vaiddas** [comment]
Hi @matt-FFFFFF  - Yes, it works fine with other TF version. 
We can close this as I am not blocked. I will try to log this with TF.
