### ISSUE TITLE
[AVM Module Issue]: App service logs are always disabled for webapps

### ISSUE THREAD

**Issue by thenewnano** [Azure/terraform-azurerm-avm-res-web-site#82]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.6.3

### Description

I see that  the part of the code passing on app service logs settings are commented out in main.webapps:51:55 this is strange as the feature is supported in the web-app and we are using it for debugging. 
Any reason why this is set always to off and if you could uncomment it ?

**Comment by donovm4** [comment]
Hi @thenewnano - I wouldn't say this is set off by default per the module. Please review the `azurerm` provider [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs) for the [web apps](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app) versus the[ function apps](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app). 

`azurerm_linux_function_app` and `azurerm_windows_function_app` accept `site_config` > `app_service_logs` via [module documentation](https://github.com/Azure/terraform-azurerm-avm-res-web-site?tab=readme-ov-file#input_site_config)

`azurerm_linux_web_app` and `azurerm_windows_wep_app` accept `logs` > `application_logs` via [module documentation](https://github.com/Azure/terraform-azurerm-avm-res-web-site?tab=readme-ov-file#input_logs)

As for why it is commented out, I haven't cleaned up some of the work/comments from the initial development - please forgive me for causing any confusion.

Please let me know how I can further assist.

**Comment by thenewnano** [comment]
OK fair enough, although it is available in azure portal for both web app and function app
