### ISSUE TITLE
[AVM Module Issue]: Missing the output `IDENTITY_PRINCIPAL_ID`

### ISSUE THREAD

**Issue by Menghua1** [Azure/terraform-azurerm-avm-res-web-site#84]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Please add the output  `IDENTITY_PRINCIPAL_ID`.
For example (azd):
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/terraform/core/host/appservice/appservicejava/appservicejava_output.tf#L5

CC: @jongio and @donovm4

**Comment by donovm4** [comment]
Hi @Menghua1 - please reference `0.7.0` for the latest outputs.

In the `examples`/`interfaces`, there is an example using the output with `managed_identites`
